config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # A user can see all the lists
  get "lists", to: "lists#index", as: :lists
  # A user can create a new list
  get "lists/new", to: "lists#new", as: :new_list
  post "lists", to: "lists#create"
   # A user can see the details of a given list and its name
   get "lists/:id", to: "lists#show", as: :list


  #  A user can add a new bookmark (movie/list pair) to an existing list
  #  Checkout simple_form docs about f.association to easily create a select dropdown for our list of movies.

  get "lists/:list_id/bookmarks", to: "bookmarks#index", as: :bookmarks
  # resources :bookmarks, only: [:index, :new, :create, :destroy]
  get "lists/:list_id/bookmarks/new", to: "bookmarks#new", as: :new_bookmark
  post "lists/:list_id/bookmarks", to: "bookmarks#create"

  #  A user can delete a bookmark from a list. How can we make a delete link again?
  delete "bookmarks/:id", to: "bookmarks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # validates comment must at least be 6 characters
  validates :comment, length: { minimum: 6 }
  # validates must be unique
  # a specific movie can only be bookmarked in one specific list
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  # has many movies (FAILED - 1)
  has_many :movies, through: :bookmarks

  # name is unique (FAILED - 6)
  # name cannot be blank (FAILED - 7)
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :restrict_with_error
  before_destroy :check_bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true


  private

   # should not be able to destroy self if has bookmarks children (FAILED - 1)
  def check_bookmarks
    if bookmarks.any?
      errors.add(:base, "Movie can not be destroyed because it has bookmarks")
      throw(:abort)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]

  def index
    @list = List.find(params[:list_id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      #  when the parameters are invalid and the list cannot be saved
      render :new
    end

  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

app/views/bookmarks/new.html.erb
<h1>Create a new Bookmark</h1>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>See all lists</h1>
<% @lists.each do |list| %>
  <ul>
    <li><%= list.name %></li>
  </ul>
<% end %>

<%= link_to "Create New List", new_list_path %>

app/views/lists/new.html.erb
<h1>Create a New List</h1>
<%= render "form" %>

app/views/lists/show.html.erb
<h1>See specific list</h1>
<p>
<%= @list.id %>
<%= @list.name %>
</p>
<%= link_to "Go back to Lists page", lists_path %>